### ISSUE TITLE
Top or bottom half of window

### ISSUE THREAD

**Issue by oalders** [Acidham/alfred-window-manager#1]
Thanks for sharing your work!

I apologize if I've missed it, but is it possible to get a keyboard shortcut to move a window to full width in the top/bottom half of the screen?

**Comment by Acidham** [comment]
Sure: https://github.com/Acidham/alfred-window-manager/releases/tag/v1.3.0

You can add additional shortcuts for your own by 
1. copy the keyboard shortcut hotkey step
2. change to a variable name, note that string
3. change keyboard shortcut
4. add the variable name noted in step 2 to the conditional step (the one with the list of variable names)
5. copy automation task and change as you want
6. connect all the WF steps, similar to the others.

**Comment by oalders** [comment]
Amazing! 🚀 Thank you so much.
